---
- name: Enable tap to click on trackpad
  shell: defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
  changed_when: false
  tags: [trackpad, preferences]

- name: Set Finder to list view by default
  shell: defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
  changed_when: false
  tags: [finder, preferences]

- name: Restart Dock and Finder to apply changes
  shell: |
    killall Dock || true
    killall Finder || true
  changed_when: false
  tags: [dock, finder, preferences]
